### ISSUE TITLE
README update suggestion

### ISSUE THREAD

**Issue by ruchaamin** [LiamCavin/Statistics.gov.scot-API#1]
Suggestion to the README to explain a bit more what the file contains, particularly if people land here from somewhere other than the HelpScout guide.

Of course, ignore if you dont think its necessary.

##################################################################

Open data for Scottish Official Statistics is available at https://statistics.gov.scot. Managed by the Scottish Goverment, this data store contains (mostly) official statistics covering a wide range of topics, and from a range of official statistics producers.

Most of the datasets held on statistics.gov.scot are published as linked open data and can be queried directly using the SPARQL API.  A small number of datasets are published as simple flat files or zipped collections of files where only the metadata can be queried. To access these datasets programmatically, first extract the current download URL from the metadata to ensure you are accessing the latest version of the data. This folder contains example code showing how to do this in R.

Published under the Open Government Licence: http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/

September 2019, Liam Cavin liam.cavin@gov.scot

**Comment by LiamCavin** [comment]
Thanks for the suggestion, that's very helpful.

L
